dist: trusty
sudo: false

git:
  depth: 8

branches:
  only:
    - master

language: python

python:
  - 2.7

install:
  - pip install -Ur requirements-ci.txt
  - pip install codecov

script:
  - pytest --cov=./cli_parsers/

after_success:
  - codecov
